logging:
  level:
    root: INFO
    io:
      github:
        hirannor:
          hexadocs: DEBUG
  file:
    path: logs

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5342/hexadocsdb
    username: root
    password: hexagonal123
  jpa:
    hibernate:
      ddl-auto: validate
  ai:
    ollama:
      base-url: http://localhost:11434
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw
  application:
    name: HexaDocs
messaging:
  rabbit:
    exchange: messages.exchange
    queue: messages.queue
    retry:
      max-attempts: 3

adapter:
  messaging: rabbitmq
  persistence: spring-data-jpa
  ai: spring-ai
  file: local-file-system-storage
  chunking: simple-text
  extraction: pdf-text

storage:
  local-file-system-path: # INSERT HERE YOUR LOCAL PATH